# Generated by Django 2.0.7 on 2018-09-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonname', models.CharField(max_length=30, verbose_name='课程名称')),
                ('teacher', models.CharField(max_length=30, verbose_name='任课老师')),
                ('lessontype', models.CharField(choices=[('人文艺术类', '人文艺术类'), ('工程技术类', '工程技术类'), ('经济管理类', '经济管理类')], max_length=30, verbose_name='课程类型')),
                ('classroom', models.CharField(max_length=30, verbose_name='上课教室')),
                ('time', models.CharField(max_length=30, verbose_name='上课时间')),
                ('week', models.CharField(max_length=30, verbose_name='起始周')),
                ('quantity', models.IntegerField(verbose_name='剩余数量')),
            ],
            options={
                'verbose_name_plural': '课程信息',
                'verbose_name': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='姓名')),
                ('class_name', models.CharField(max_length=50, verbose_name='所在班级')),
            ],
            options={
                'verbose_name_plural': '学生信息',
                'verbose_name': '学生信息',
            },
        ),
    ]
