# Generated by Django 2.0.7 on 2018-09-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_name2', to='lesson.UserForm', verbose_name='所在班级')),
            ],
            options={
                'verbose_name': '选课结果',
                'verbose_name_plural': '选课结果',
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.CharField(max_length=30, verbose_name='起始-结束周'),
        ),
        migrations.AddField(
            model_name='result',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom2', to='lesson.lesson', verbose_name='上课教室'),
        ),
        migrations.AddField(
            model_name='result',
            name='lessonname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessonname2', to='lesson.lesson', verbose_name='课程名称'),
        ),
        migrations.AddField(
            model_name='result',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name2', to='lesson.UserForm', verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='result',
            name='teahcer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher2', to='lesson.lesson', verbose_name='任课老师'),
        ),
        migrations.AddField(
            model_name='result',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='time2', to='lesson.lesson', verbose_name='上课时间'),
        ),
        migrations.AddField(
            model_name='result',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='username2', to='lesson.UserForm', verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='result',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='week2', to='lesson.lesson', verbose_name='起始-结束周'),
        ),
    ]
