# Generated by Django 2.0.7 on 2018-09-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_auto_20180926_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='class_name2',
            field=models.CharField(max_length=30, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='result',
            name='classroom2',
            field=models.CharField(max_length=30, verbose_name='上课教室'),
        ),
        migrations.AlterField(
            model_name='result',
            name='lessonname2',
            field=models.CharField(max_length=30, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='result',
            name='name2',
            field=models.CharField(max_length=30, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='result',
            name='teahcer2',
            field=models.CharField(max_length=30, verbose_name='任课老师'),
        ),
        migrations.AlterField(
            model_name='result',
            name='time2',
            field=models.CharField(max_length=30, verbose_name='上课时间'),
        ),
        migrations.AlterField(
            model_name='result',
            name='username2',
            field=models.CharField(max_length=30, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='result',
            name='week2',
            field=models.CharField(max_length=30, verbose_name='起始-结束周'),
        ),
    ]
