# Generated by Django 2.0.7 on 2018-09-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_auto_20180926_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='class_name2',
            new_name='rclass_name',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='classroom2',
            new_name='rclassroom',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='lessonname2',
            new_name='rlessonname',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='name2',
            new_name='rname',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='teahcer2',
            new_name='rteahcer',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='time2',
            new_name='rtime',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='username2',
            new_name='rusername',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='week2',
            new_name='rweek',
        ),
    ]
