# Generated by Django 2.0.7 on 2019-03-07 12:12

from django.db import migrations, models
import lesson.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_auto_20180926_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='u_ticket',
        ),
        migrations.AddField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=lesson.models.lesson.get_photo, verbose_name='相关照片'),
        ),
    ]
