# Generated by Django 2.0.7 on 2019-03-09 16:39

from django.db import migrations, models
import lesson.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_auto_20190307_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='movie',
            field=models.FileField(default='videos/default.mp4', max_length=200, upload_to=lesson.models.lesson.get_movie, verbose_name='视频文件'),
        ),
    ]
