# Generated by Django 2.0.7 on 2019-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_lesson_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='e_mail',
            field=models.CharField(default='', max_length=30, verbose_name='邮箱'),
        ),
    ]
