# Generated by Django 2.0.7 on 2019-03-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_students_e_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='e_mail',
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='邮箱'),
        ),
    ]
