# Generated by Django 2.0.7 on 2018-09-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_auto_20180926_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='rlessontype',
            field=models.CharField(max_length=30, verbose_name='课程类型'),
        ),
    ]
